version: "3.0"

services:
  nodejs:
    image: stock-exch
    restart: on-failure
    build:
      #context: ./
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cloud_stocks