apiVersion: v1
kind: Service
metadata:
  name: user-stock-service
spec:
  type: NodePort
selector:
  app: metrics
department: stock_exch
ports:
- protocol: TCP
  port: 8080
  targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-stock-service

  selector:
    matchLabels:
      app: metrics
      department: stock_exch
replicas: 1
template:
  metadata:
    labels:
      app: metrics
      department: stock_exch
      role: rolling-update

  terminationGracePeriodSeconds: 30
  containers:
  - name: user-stock-service
  image:
    "324487185086.dkr.ecr.us-east-2.amazonaws.com/user-service:latest"
imagePullPolicy: "Never"
env:
- name: "PORT"
value: "8080"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-service

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-stock-service
minReplicas: 1
maxReplicas: 10
targetCPUUtilizationPercentage: 50